services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  presenceapi:
    image: ${DOCKER_REGISTRY-}presenceapi
    build:
      context: .
      dockerfile: PresenceApi/PresenceApi/Dockerfile
