services:
  mongo-express:
    ports:
      - "27016:27016"  # Port for Mongo Express web UI
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    volumes:
      - mongo-data:/data/db
    depends_on:
      - mongo

  presenceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MongoDBSettings__AtlasURI=mongodb://root:example@mongo:27017/
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on: 
     - mongo-express
     - mcc
  

  mcc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__StringConnection=Host=dpg-csce5cl6l47c73dvujd0-a.oregon-postgres.render.com;Port=5432;Username=master;Password=ysmbk03l4PwVmayhdEEHBdwKGsRJbmYy;Database=postgresmoutscompass
      - Jwt__Key=1a28bedb5a055526375fdc044d3133ffa318e9432b4e2e2b890135058e7a032a515aede2c28bae62e7946736b72fbd36a40c678b6a00b28e9c77ca547f4d657d3465115226947adc960815f168e48fb450646bca8c771cdea1538ba17449c4e438fe77fd77ffaabeeafc107aec8cc978d9a9a14be6f148b1e5d5a8fe4700d551171e811901a89221ac766c91b368a3397c742d2b901141ce44e30c9fcfba5f1777f54cfeff33ccf25ba34f5f0c35302985e1b72bd9c5bcce7cc369ad320d66837561dfbfc4035966b91edb4d00cdf16a037ef974118520c565a4a49c6f084f3f3c6fece3f1844a554de8a68d5505e1b29f2b3545597c1eabd99ff1824a221d8e
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro



